### ISSUE TITLE
Open images even when the file extension is not correct

### ISSUE THREAD

**Issue by gpunktschmitz** [linuxmint/xviewer#115] opened 2020-10-27 05:39 UTC
```
 * Xviewer 2.6.2 (xviewer --version)
 * Mint 20 - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**
Occasionally I receive JPEG files with the file extension "PNG". This results in Xviewer showing an error when trying to open the file. "Fatal error reading PNG image file: Not a PNG file"
One has to run "file t.PNG" to find out which file extension it should have and rename it.

**Steps to reproduce**
Rename a JPEG file to the file extension "PNG" and try to open it.

**Expected behaviour**
Xviewer should open the JPEG file and show a message that the extension is wrong (and maybe also suggest renaming it for the user).

**Other information**

**Comment by icarter09** [comment] 2020-11-11 17:02
Closing since it's a duplicate of #104

**Closed by icarter09** 2020-11-11 17:02 UTC
