### ISSUE TITLE
Support webp?

### ISSUE THREAD

**Issue by abcfy2** [linuxmint/xviewer#23] opened 2016-12-26 09:16 UTC
Will xviewer plan to support webp image?

**Comment by artik** [comment] 2019-03-05 14:09
Any news about support of webp format?

**Comment by swiftech** [comment] 2019-06-14 09:00
+1

**Comment by HotElectron** [comment] 2019-06-30 03:19
bump

**Comment by josinaldobarbosa** [comment] 2019-07-14 14:21
:/  not yet

**Comment by HoffmannP** [comment] 2019-11-21 12:15
+1

**Comment by svastian99** [comment] 2020-01-08 13:46
Please! add the support for Webp files

**Comment by navin09** [comment] 2020-02-25 07:18
+1   Pretty please? With sugar on top?

**Comment by raniesantos** [comment] 2020-03-18 20:20
The use of webp is slowly spreading, it would be good to have this feature now.

**Comment by thunderamur** [comment] 2020-05-05 15:45
I need this feature. For for this feature request!

**Comment by Arinelle** [comment] 2020-05-07 23:04
Yes please, this is becoming very handicapping!

**Comment by cptX** [comment] 2020-09-22 07:04
4 years since the first request? Are you planning to implement this soon? Webp format is used more and more nowadays!

**Comment by craigs100** [comment] 2020-10-09 22:33
Please get webp sorted. There are web developers needing this. webp is now supported by the majority of browsers.

**Comment by mbnoimi** [comment] 2020-10-15 23:46
+1

**Comment by iSWORD** [comment] 2021-02-03 04:24
I just built from source and installed `libwebp6` and it seems to be working.. 🤔

**Comment by cptX** [comment] 2021-02-03 09:24
Have you build xviewer from source you mean? When is this going to be streamed to the repositories?

**Comment by iSWORD** [comment] 2021-02-03 14:13
Yeah I built xviewer from source then installed libwebp from repos.

It seems the support for webp is really basic though. Navigating with left and right keys doesn't show any other images than the one you opened initially and some webp images still fail to load.

I then updated to 20.1 and realized it is in the repos, but then I uninstalled xviewer and started using gthumb instead :(

**Comment by picarica** [comment] 2021-04-10 14:32
is it supported? i am using newest 20.1 focal and yet i cant open .webp images even with libwebp6 installed

**Comment by craigs100** [comment] 2021-04-10 16:40
I've given up and just use gThumb for svg's

**Comment by clefebvre** [comment] 2021-05-14 12:43
This is upstream from us, it's not something we can fix in xviewer itself. The picture isn't loaded by xviewer directly but by GdkPixbufLoader.

See:

- https://bugzilla.gnome.org/show_bug.cgi?id=700751
- https://github.com/aruiz/webp-pixbuf-loader/issues/9
- https://bugs.launchpad.net/ubuntu/+source/gdk-pixbuf/+bug/1864215
- https://gitlab.gnome.org/GNOME/eog/-/issues/45

Once this is fixed upstream xviewer will be able to load webp pictures without any code changes. What we'll need to do though, when that happens, and depending on how it's done, is make xviewer accept the mimetype (that's really easy though) so that you can double-click the file to open xviewer.

In the meantime you can associate pix to webp images, it supports it well.

@iSWORD if you can shed more light on how you got this to work... I've got libweb6 here and xviewer still fails to load that format.

**Comment by iSWORD** [comment] 2021-05-16 10:16
@clefebvre I have no idea how I got it to work. I've been trying to reproduce it in a VM for two hours to no avail.

I still have my installation that got it to work, I'm not sure what to dump to help. My package list is HUGE and I have no clue what to leave out.

![image](https://user-images.githubusercontent.com/1176779/118393662-7f9ba100-b640-11eb-8d7d-a2d0f435fb24.png)

**Comment by cptX** [comment] 2021-05-17 05:53
Mine is version 2.4.3 and doesn't open it 
![image](https://user-images.githubusercontent.com/9040042/118438612-5127cf80-b6ed-11eb-90fb-16c7504c20d6.png)

**Comment by Hordeking** [comment] 2021-06-03 00:55
I'm on Mint 20.1, xviewer 2.8.3. libwebp6 is installed, I'm getting nothing. Is this an issue with the package maintainer not building against the libwebp library possibly? I don't know who that is or I would ping them to loop them in.

**Comment by tudo75** [comment] 2021-07-11 18:00
> This is upstream from us, it's not something we can fix in xviewer itself. The picture isn't loaded by xviewer directly but by GdkPixbufLoader.
> 
> See:
> 
>     * https://bugzilla.gnome.org/show_bug.cgi?id=700751
> 
>     * [/usr/bin/gdk-pixbuf-query-loaders is no more available in debian and ubuntu aruiz/webp-pixbuf-loader#9](https://github.com/aruiz/webp-pixbuf-loader/issues/9)
> 
>     * https://bugs.launchpad.net/ubuntu/+source/gdk-pixbuf/+bug/1864215
> 
>     * https://gitlab.gnome.org/GNOME/eog/-/issues/45
> 
> 
> Once this is fixed upstream xviewer will be able to load webp pictures without any code changes. What we'll need to do though, when that happens, and depending on how it's done, is make xviewer accept the mimetype (that's really easy though) so that you can double-click the file to open xviewer.
> 
> In the meantime you can associate pix to webp images, it supports it well.
> 
> @iSWORD if you can shed more light on how you got this to work... I've got libweb 0.6.1-2 here and xviewer still fails to load that format, recompiling it doesn't help.

pqiv [https://github.com/phillipberndt/pqiv](https://github.com/phillipberndt/pqiv) seems to use gtk3 and gdk-pixbuf and is able to display webp images (with libwep installed). May they have found a working solution?

**Comment by tudo75** [comment] 2021-07-11 23:28
I tried this and seems to work
[https://salsa.debian.org/okias-guest/webp-pixbuf-loader](https://salsa.debian.org/okias-guest/webp-pixbuf-loader)

**Comment by joka42** [comment] 2021-07-28 07:01
@tudo75 what do you have to do in order to get it to work? (after building and installing as said in the readme?)

**Comment by tudo75** [comment] 2021-07-28 11:56
@joka42 I followed the build instruction for ubuntu (I'm on linux mint 20.2 xfce) and installed. you can check after install if file exist
/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-webp.so
 and 
there are these lines 
```
"/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-webp.so"
"webp" 5 "gdk-pixbuf" "The WebP image format" "LGPL"
"image/webp" "audio/x-riff" ""
"webp" ""
"RIFFsizeWEBP" "    xxxx    " 100
```
in
/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache

**Comment by joka42** [comment] 2021-07-28 15:51
@tudo75 I am in Manjaro (Cinnamon) and I could find the libs in `/usr/lib/gdk-pixbuf-2.0/...` also the `loaders.cache` files contained the lines you mentioned, but still get the following error in xviewer:
![image](https://user-images.githubusercontent.com/68659955/127354618-c70507ff-f2a6-40c6-8dfd-224670c159bc.png)

**Comment by tudo75** [comment] 2021-09-24 00:07
@joka42 
there is a pull request for the webp-pixbuf-loader that add animated webp support
you an find it here
[https://github.com/alanhaw/webp-pixbuf-loader](https://github.com/alanhaw/webp-pixbuf-loader)
And here there is the discussion
[https://github.com/aruiz/webp-pixbuf-loader/pull/30](https://github.com/aruiz/webp-pixbuf-loader/pull/30)
I installed and tested it and worked with some animated images found after a rapid search

**Comment by haggen88** [comment] 2021-11-26 17:21
I followed the steps in this [guide](https://codepre.com/use-the-webp-gdk-pixbuf-loader-library-to-display-webp-thumbnails-in-gtk-applications-nautilus-thunar-etc.html) and [webp-pixbuf-loader](https://github.com/aruiz/webp-pixbuf-loader) worked for me:

![xviewer - webp support](https://user-images.githubusercontent.com/68134588/143614654-b85026ff-bfe4-4330-b129-34f1cba50c95.png)

**Comment by danielp96** [comment] 2022-01-11 19:57
The guide haggen88 mentioned worked for me on Mint 20.3 and xviewer 3.2.4.
Webp files now show thumbnails on nemo and can be viewed on xviewer.

**Comment by artik** [comment] 2022-01-11 20:18
It worked for me also, thanks @haggen88 
Having it packaged in mint would be a good thing as this format starts to be quite spreaded

**Comment by joka42** [comment] 2022-01-25 21:55
Thanks @tudo75 I built the [repo](https://github.com/alanhaw/webp-pixbuf-loader)  from source and it works well with animated webp images in mint 20.3.

**Comment by joka42** [comment] 2022-02-04 10:23
The open MR has been merged to also support animated webp images. Here is the latest release: https://github.com/aruiz/webp-pixbuf-loader/releases/tag/0.0.4

**how to**

install dependencies:
`sudo apt install libwebp-dev libgdk-pixbuf2.0-dev libgtk-3-dev meson build-essential`
 
build from source and install as described in the readme.md.

**Comment by haggen88** [comment] 2022-05-05 16:13
There are good news. It is part of the roadmap:
https://tree.taiga.io/project/linuxmint-linux-mint-21-1/us/216

**Closed** 2022-07-01 13:19 UTC
Labels: FEATURE REQUEST
